### ISSUE TITLE
`uv pip install -e .` fails with "Multiple top-level packages discovered in a flat-layout: ['configs', 'verifiers']"

### ISSUE THREAD

**Issue by skoshx** [willccbb/verifiers#41]
This can be just fixed with adding this to `pyproject.toml`

```toml
[tool.setuptools]
packages = ["verifiers"]

```

I can do a PR for this
